name: traktx
description: A Dart client library for the Trakt API.
version: 1.0.0
repository: https://github.com/crxssed7/traktx

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  http: ^1.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
